### ISSUE TITLE
Gradle 4.4, app crash on getAll?

### ISSUE THREAD

**Issue by giacomocerquone** [rt2zz/react-native-contacts#303]
Hi all, recently I updated my rn project in order to use gradle 4.4 (because of firebase integration) and suddenly my app started crashing everytime I call the getAll method.

Sadly I'm not even able to debug it natively since I've got some gradle problems there

Is it possible that these two things are correlated?

I also tried to apply this PR #258 manually, but it didn't work

**Comment by giacomocerquone** [comment]
Thanks, we've solved it!
Basically we changed the target sdk too while editing the build.gradle and with that one (27), it's needed the permissions request... without it the app crashes

PS. I'm strongly convinced that it depends on the target sdk and not on the android OS version as someone else stated in some other issue, this because I've never changed the os version on the emulator

**Comment by morenoh149** [comment]
Got it. I'll leave this open in case others run into issues as well.

**Comment by dltjiangfeipeng** [comment]
我也遇到这个问题

**Comment by giacomocerquone** [comment]
@dltjiangfeipeng really?
So you believe we should all know your language? 😅

**Comment by dltjiangfeipeng** [comment]
How did you fix it

**Comment by dltjiangfeipeng** [comment]
@giacomocerquone   我刚遇到，还没有解决，谢谢

**Comment by ziftinpeki** [comment]
+1

**Comment by giacomocerquone** [comment]
I wrote in my second-last comment (https://github.com/rt2zz/react-native-contacts/issues/303#issuecomment-392618137) how I fixed it guys... if this doesn't work for you, sadly I can't do nothing! The library too has its problems, so it may be something else (see this for example #247 or this #291)

**Comment by ziftinpeki** [comment]
Thanks @giacomocerquone 

i tried that and it doesnt work for me :( still get crash when i called getAll...

**Comment by steelbrain** [comment]
Fix is up in https://github.com/rt2zz/react-native-contacts/pull/324
