### ISSUE TITLE
Auto Linking + My version of MainApplication.java is different from the installation instructions

### ISSUE THREAD

**Issue by Bilal-Abdeen** [rt2zz/react-native-contacts#437]
I have 2 issue, which might be related to each other. 

1. My version of the file MainApplication.java is different from the installation instructions. 
The installation instructions says: 
```
import com.rt2zz.reactnativecontacts.ReactNativeContacts; // <--- import
public class MainActivity extends ReactActivity {
  ......     
  @Override
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
      new MainReactPackage(),
      new ReactNativeContacts()); // <------ add this
    }
    ......
  }
```

While my file looks like the following: 
```
import com.rt2zz.reactnativecontacts.ReactNativeContacts; // <--- I added this 
public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

I was able to successfully apply the rest of the installation instructions. **What should I do about this file?**

2. My 2nd issue is that when I start my app on the Android emulator (by typing react-native run-android), I get the following error message. Most of the time, it seems that the app starts successfully. However, I am not comfortable seeing an error message. 

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-contacts (to unlink run: "react-native unlink react-native-contacts")
```
I tried to run "react-native unlink react-native-contacts". This resulted in removing all of the changes, which I made to 3 files by following the installation instructions. However, the error message is still displayed. 

Following is an extract of the package.json file.
```
{
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.1",
    "@react-native-community/netinfo": "^4.2.2",
    "@redux-offline/redux-offline": "^2.5.2-native.1",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-contacts": "^5.0.3",
    ....
    "react-navigation": "^4.0.6",
    "react-navigation-stack": "^1.8.0",
    "react-navigation-tabs": "^2.5.4",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    .... 
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/runtime": "^7.6.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.4.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by morenoh149** [comment]
this first issue is fixed, was a consequence of updating the library for newer versions of android and missing that the class signature changed.

Always refer to the example app for how things should work https://github.com/rt2zz/react-native-contacts/blob/master/example/android/app/src/main/java/com/example/MainApplication.java

Could you make an issue just for the second bug please. We do not recommend linking as it has worked inconsistently in the past. If modern versions of rn say linking should work then we need a ticket to make linking work with this library.

**Comment by Bilal-Abdeen** [comment]
@morenoh149 Thank you for the feedback. Actually, I am still not sure what to do about the 1st one. 

The example, which you referred me to, has: 
``` 
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNGestureHandlerPackage(),
            new ReactNativeContacts()
      );
    }
``` 
While my file has: 
```
    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      return packages;
    }
```

**Should I replace these sections, with each other, or combine them somehow?**

**Comment by morenoh149** [comment]
looks like rn native has changed the look of this function. try something like
```
...
      List<ReactPackage> packages = new PackageList(this).getPackages();
      packages.add(new ReactNativeContacts());
      return packages;
...
```
note I'm just following what the comment says. This is new to everyone.

**Comment by Bilal-Abdeen** [comment]
@morenoh149 Thanks for the super quick response. 

Let me clarify that despite these 2 issues, my code seems to work fine on an Android emulator (I am able to read the device's contacts list). 

I thought of raising these 2 issues because I was not sure if something would break in the future. Probably, the new version of React-Native does not need registration of ReactNativeContacts() in MainApplication.java! 

I have done the change, which you suggested. After running (react-native run-android), I got the following error message 
```
Native module Contacts tried to override ContactsManager. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true
```

**Comment by morenoh149** [comment]
:/ sounds like we no longer need to register the lib in the java code? not sure.

**Comment by nol13** [comment]
As far as I can tell the podfile and MainApplication.java changes are both not needed. Had to delete the references from podfile.lock and reinstall to get rid of the 'linked manually' warning. Also permissions might nit be needed(?) if you only need to use openContactForm.

**Comment by morenoh149** [comment]
@nol13 yeah, the permissions you need will depend on what apis you use.
